apiVersion: apps/v1
kind: Deployment
metadata:
  name: monolithic-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monolithic-app
  template:
    metadata:
      labels:
        app: monolithic-app
    spec:
      containers:
      - name: monolithic-app
        image: monolithic-app:latest
        ports:
        - containerPort: 5000
        - containerPort: 80
        env:
        - name: MONGO_URI
          value: "mongodb://mongo:27017/dev"
---
apiVersion: v1
kind: Service
metadata:
  name: monolithic-app-service
spec:
  selector:
    app: monolithic-app
  ports:
    - name: backend
      port: 5000
      targetPort: 5000
    - name: frontend
      port: 80
      targetPort: 80
  type: LoadBalancer